- hosts: localhost
  vars_files:
    - "dict_example.yml"

  tasks:
    - name: Create StatusCake tests
      status_cake_test:
        api_key:   "som3thing1se3cret"
        state:     "present"
        name:      "{{ item.value.url }}"
        url:       "{{ item.value.url }}"
        test_tags: "something"
        test_type: "HTTP"
        check_rate: 300
      loop: "{{ example | dict2items }}"
