- hosts: localhost
  vars_files:
    - "dict_example.yml"

  tasks:
    - name: Create StatusCake tests
      status_cake_test: 
        username:  "example_user"
        api_key:   "som3thing1se3cret"
        state:     "present"
        name:      "{{ item.value.url }}"
        url:       "{{ item.value.url }}"
        test_tags: "something"
        test_type: "HTTP"
        check_rate: 300
      with_dict:    "{{ example }}"

    - name: Create StatusCake SSL checks
      status_cake_ssl:
        username:       "example_user"
        api_key:        "som3thing1se3cret"
        state:          "present"
        domain:         "{{ item.value.domain }}"
        check_rate:     300
        contact:        "1234,42"
        alert_at:       "59,60,61"
        alert_reminder: true
        alert_expiry:   false
        alert_broken:   false
        alert_mixed:    false
      with_dict:        "{{ example_ssl }}"
